"""Render ProviderReports as a monthly markdown report.

Sections:
1. 💰 Total month-to-date spend
2. ⚠️ Waste findings sorted by estimated savings (highest first)
3. 📊 Per-provider breakdown
4. ⚠️ Providers unavailable
"""
from __future__ import annotations
from datetime import datetime, timezone
from .providers.base import ProviderReport


SEVERITY_ICON = {"alert": "🚨", "warn": "⚠️", "info": "💡"}


def compose_report(reports: list[ProviderReport],
                   *, title: str | None = None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m")
    title = title or f"Cost Audit — {now}"

    out: list[str] = [f"# {title}", ""]

    # Total spend
    total_mtd = sum(r.spend_usd_mtd for r in reports if not r.error)
    total_subs = sum(r.subscription_cost_usd_monthly for r in reports if not r.error)
    out += ["## 💰 Total spend", "",
            f"- **MTD spend across stack:** ${total_mtd:.2f}",
            f"- **Subscription baselines (locked-in):** ${total_subs:.2f}/mo",
            ""]

    # Waste findings — flat list across all providers, sorted by savings desc
    findings: list[tuple[str, "WasteFinding"]] = []
    for r in reports:
        for f in r.waste_findings:
            findings.append((r.provider, f))
    findings.sort(key=lambda x: -x[1].estimated_monthly_savings_usd)

    if findings:
        total_savings = sum(f.estimated_monthly_savings_usd
                            for _, f in findings)
        out += [f"## 🔍 Waste findings — potential savings: ${total_savings:.2f}/mo",
                ""]
        for provider, f in findings:
            icon = SEVERITY_ICON.get(f.severity, "·")
            saving = (f" (~${f.estimated_monthly_savings_usd:.2f}/mo)"
                      if f.estimated_monthly_savings_usd else "")
            out.append(f"- {icon} **[{provider}]** {f.title}{saving}")
            out.append(f"  - {f.detail}")
        out.append("")

    # Per-provider breakdown
    out += ["## 📊 By provider", ""]
    for r in sorted(reports, key=lambda r: -r.spend_usd_mtd):
        if r.error:
            continue
        out.append(f"### {r.provider}")
        out.append(f"- **Spend MTD:** ${r.spend_usd_mtd:.2f}")
        if r.subscription_cost_usd_monthly:
            out.append(f"- **Subscription:** ${r.subscription_cost_usd_monthly:.2f}/mo")
        for k, v in r.usage_units.items():
            if isinstance(v, float) and v != int(v):
                out.append(f"- {k}: {v:.2f}")
            else:
                out.append(f"- {k}: {int(v) if isinstance(v, (int, float)) else v}")
        out.append("")

    # Failures
    failed = [r for r in reports if r.error]
    if failed:
        out += ["## ⚠️ Providers unavailable", ""]
        for r in failed:
            out.append(f"- **{r.provider}** — {r.error}")
        out.append("")

    out += ["---",
            f"_Generated by cost-audit-agent at "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_"]

    return "\n".join(out)
